// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/snsevents"

func main() {
	// New constructs an SNS-backed driver.

	// Example: construct an SNS driver
	driver, _ := snsevents.New(snsevents.Config{
		Region:   "us-east-1",
		Endpoint: "http://127.0.0.1:4566",
	})
	_ = driver
}
