// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Count returns the total number of recorded publishes.

	// Example: count recorded publishes
	type UserCreated struct {
		ID string `json:"id"`
	}

	fake := events.NewFake()
	_ = fake.Bus().Publish(UserCreated{ID: "123"})
	fmt.Println(fake.Count())
	// Output: 1
}
