// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/kafkaevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// PublishContext publishes a topic payload to Kafka.

	// Example: publish a raw message through Kafka
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	_ = driver.PublishContext(context.Background(), eventscore.Message{
		Topic:   "users.created",
		Payload: []byte(`{"id":"123"}`),
	})
}
