// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/redisevents"
)

func main() {
	// Ready checks Redis connectivity.

	// Example: check Redis connectivity
	driver, _ := redisevents.New(redisevents.Config{Addr: "127.0.0.1:6379"})
	fmt.Println(driver.Ready(context.Background()) == nil)
	// Output: true
}
