// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/snsevents"

func main() {
	// Config configures SNS transport construction.

	// Example: define SNS driver config
	cfg := snsevents.Config{
		Region:   "us-east-1",
		Endpoint: "http://127.0.0.1:4566",
	}
	_ = cfg

}
