// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Bus returns the wrapped API to inject into code under test.

	// Example: inject the fake bus into application code
	fake := events.NewFake()
	bus := fake.Bus()
	fmt.Println(bus.Ready() == nil)
	// Output: true
}
