// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// NewFake creates a new fake event harness backed by the root sync bus.

	// Example: construct a recording fake
	fake := events.NewFake()
	fmt.Println(fake.Count())
	// Output: 0
}
