// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/natsjetstreamevents"

func main() {
	// Config configures NATS JetStream transport construction.

	// Example: define NATS JetStream driver config
	cfg := natsjetstreamevents.Config{URL: "nats://127.0.0.1:4222"}
	_ = cfg

}
