// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/redisevents"
)

func main() {
	// Config configures Redis transport construction.

	// Example: define Redis driver config with all fields
	cfg := redisevents.Config{
		Addr:   "127.0.0.1:6379",
		Client: nil, // default: nil constructs a client from Addr
	}
	fmt.Println(cfg.Addr)
	// Output: 127.0.0.1:6379
}
