package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	apiStart       = "<!-- api:embed:start -->"
	apiEnd         = "<!-- api:embed:end -->"
	testCountStart = "<!-- test-count:embed:start -->"
	testCountEnd   = "<!-- test-count:embed:end -->"
)

func main() {
	root, err := repoRoot()
	if err != nil {
		fail(err)
	}

	readmePath := filepath.Join(root, "README.md")
	body, err := os.ReadFile(readmePath)
	if err != nil {
		fail(err)
	}

	updated, err := replaceAPISection(string(body), renderAPISection())
	if err != nil {
		fail(err)
	}
	if err := validateReadmeBody(updated, defaultRequiredContent()); err != nil {
		fail(err)
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		fail(err)
	}

	fmt.Println("README check passed")
}

func validateReadme(path string, required []string) error {
	body, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return validateReadmeBody(string(body), required)
}

func validateReadmeBody(body string, required []string) error {
	for _, needle := range required {
		if !strings.Contains(body, needle) {
			return fmt.Errorf("README missing required content %q", needle)
		}
	}
	return nil
}

func defaultRequiredContent() []string {
	return []string{
		"# events",
		"## Installation",
		"## Drivers",
		"## Quick Start",
		"## Delivery Semantics",
		"## events vs queue",
		"## API Index",
		"events.NewSync",
		testCountStart,
		testCountEnd,
		apiStart,
		apiEnd,
	}
}

func renderAPISection() string {
	lines := []string{
		apiStart,
		"_generated by `go run ./docs/readme`_",
		"",
		"### Core",
		"",
		"| Package | API | Purpose |",
		"| --- | --- | --- |",
		"| `events` | `New`, `NewSync`, `NewNull`, `WithCodec` | Root constructors and options for the typed bus. |",
		"| `events` | `Bus.Publish`, `Bus.PublishContext` | Publish typed events through the configured transport. |",
		"| `events` | `Bus.Subscribe`, `Bus.SubscribeContext` | Register typed handlers and receive a closable subscription. |",
		"| `events` | `Bus.Ready`, `Bus.ReadyContext`, `Bus.Driver`, `Bus.Close` | Transport health, backend identity, and shutdown. |",
		"| `events` | `NewFake` | Lightweight root fake for application tests. |",
		"| `eventscore` | `Driver`, `Message`, `DriverAPI`, `Subscription` | Driver-facing transport contracts. |",
		"| `eventstest` | `RunBusContract`, `RunNullBusContract` | Shared contract harness for bus implementations. |",
		"| `eventsfake` | `New` | Assertion-oriented fake/testing helper module. |",
		"",
		"### Driver Modules",
		"",
		"| Package | Constructor | Purpose |",
		"| --- | --- | --- |",
		"| `driver/natsevents` | `natsevents.New` | NATS subject-based distributed fan-out transport. |",
		"| `driver/redisevents` | `redisevents.New` | Redis pub/sub distributed fan-out transport. |",
		"| `driver/kafkaevents` | `kafkaevents.New` | Kafka topic-based fan-out compatibility transport. |",
		"| `driver/gcppubsubevents` | `gcppubsubevents.New` | Google Pub/Sub emulator-backed transport. |",
		apiEnd,
	}
	return strings.Join(lines, "\n")
}

func replaceAPISection(body string, api string) (string, error) {
	start := strings.Index(body, apiStart)
	end := strings.Index(body, apiEnd)
	if start == -1 || end == -1 || end < start {
		return "", fmt.Errorf("README missing %s/%s markers", apiStart, apiEnd)
	}
	end += len(apiEnd)
	return body[:start] + api + body[end:], nil
}

func repoRoot() (string, error) {
	root, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return filepath.Clean(filepath.Join(root, "..")), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
