// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// SubscribeContext registers a typed handler.

	// Example: subscribe with a caller context
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	sub, _ := bus.SubscribeContext(context.Background(), func(ctx context.Context, event UserCreated) error {
		fmt.Println(event.ID, ctx != nil)
		return nil
	})
	defer sub.Close()
	_ = bus.PublishContext(context.Background(), UserCreated{ID: "123"})
	// Output: 123 true
}
