// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events"
)

func main() {
	// SubscribeContext registers a typed handler.

	// Example: subscribe with a caller context
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	sub, _ := bus.SubscribeContext(context.Background(), func(ctx context.Context, event UserCreated) error {
		_ = ctx
		_ = event
		return nil
	})
	defer sub.Close()
}
