// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/kafkaevents"
)

func main() {
	// New constructs a Kafka-backed driver.

	// Example: construct a Kafka driver
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	fmt.Println(driver != nil)
	// Output: true
}
