// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/kafkaevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// SubscribeContext subscribes to a Kafka topic and forwards messages.

	// Example: subscribe to a Kafka topic
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	sub, _ := driver.SubscribeContext(context.Background(), "users.created", func(ctx context.Context, msg eventscore.Message) error {
		_ = ctx
		_ = msg
		return nil
	})
	fmt.Println(sub != nil)
	// Output: true
}
