// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/gcppubsubevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// PublishContext publishes a topic payload to Google Pub/Sub.

	// Example: publish a raw message through Google Pub/Sub
	driver, _ := gcppubsubevents.New(context.Background(), gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	})
	_ = driver.PublishContext(context.Background(), eventscore.Message{
		Topic:   "users.created",
		Payload: []byte(`{"id":"123"}`),
	})
}
