// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/natsevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// PublishContext publishes a topic payload to NATS.

	// Example: publish a raw message through NATS
	driver, _ := natsevents.New(natsevents.Config{URL: "nats://127.0.0.1:4222"})
	_ = driver.PublishContext(context.Background(), eventscore.Message{
		Topic:   "users.created",
		Payload: []byte(`{"id":"123"}`),
	})
}
