// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// NewSync constructs the root sync bus.

	// Example: construct a sync bus
	bus, _ := events.NewSync()
	fmt.Println(bus.Driver())
	// Output: sync
}
