// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Ready performs a background-context readiness check.

	// Example: check readiness through the interface
	api, _ := events.NewSync()
	var bus events.API = api
	fmt.Println(bus.Ready() == nil)
	// Output: true
}
