// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/kafkaevents"

func main() {
	// Config configures Kafka transport construction.

	// Example: define Kafka driver config with all fields
	cfg := kafkaevents.Config{
		Brokers: []string{"127.0.0.1:9092"},
		Dialer:  nil, // default: nil uses a zero-value kafka.Dialer
		Writer:  nil, // default: nil builds a writer with single-message, auto-topic defaults
	}
	_ = cfg
}
