// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/snsevents"

func main() {
	// Config configures SNS transport construction.

	// Example: define SNS driver config with all fields
	cfg := snsevents.Config{
		Region:            "us-east-1",
		Endpoint:          "http://127.0.0.1:4566", // default: "" uses normal AWS resolution
		SNSClient:         nil,                     // default: nil creates a client from Region and Endpoint
		SQSClient:         nil,                     // default: nil creates a client from Region and Endpoint
		TopicNamePrefix:   "events-",               // default: ""
		QueueNamePrefix:   "events-",               // default: ""
		WaitTimeSeconds:   1,                       // default: 1
		VisibilityTimeout: 30,                      // default: 30
	}
	_ = cfg
}
