// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// PublishContext dispatches an event with the provided context.

	// Example: publish with a caller context
	type UserCreated struct {
		ID string `json:"id"`
	}

	api, _ := events.NewSync()
	var bus events.API = api
	_, _ = bus.Subscribe(func(ctx context.Context, event UserCreated) error {
		fmt.Println(event.ID, ctx != nil)
		return nil
	})
	_ = bus.PublishContext(context.Background(), UserCreated{ID: "123"})
	// Output: 123 true
}
