// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/redisevents"

func main() {
	// Driver reports the active backend kind.

	// Example: inspect the driver kind
	driver, _ := redisevents.New(redisevents.Config{Addr: "127.0.0.1:6379"})
	_ = driver
}
