// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Subscription releases a subscription when closed.

	// Example: unsubscribe from a typed event
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	sub, _ := bus.Subscribe(func(event UserCreated) {
		fmt.Println("received", event.ID)
	})
	_ = bus.Publish(UserCreated{ID: "123"})
	_ = sub.Close()
	_ = bus.Publish(UserCreated{ID: "456"})
	// Output: received 123
}
