// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Subscription releases a subscription when closed.

	// Example: close a subscription when done
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	sub, _ := bus.Subscribe(func(UserCreated) {})
	fmt.Println(sub.Close() == nil)
	// Output: true
}
