// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// TopicEvent overrides the derived topic for an event.

	// Example: override the derived topic
	var event events.TopicEvent
	fmt.Println(event == nil)
	// Output: true
}
