// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/redisevents"

func main() {
	// Config configures Redis transport construction.

	// Example: define Redis driver config
	cfg := redisevents.Config{Addr: "127.0.0.1:6379"}
	_ = cfg

}
