// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/kafkaevents"

// main keeps this generated example compile-checked.
func main() {
	// Config configures Kafka transport construction.

	// Example: define Kafka driver config
	cfg := kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}}
	_ = cfg

}
