// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// ReadyContext reports whether the bus is ready.

	// Example: check readiness with a caller context
	bus, _ := events.NewSync()
	fmt.Println(bus.ReadyContext(context.Background()) == nil)
	// Output: true
}
