// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// WithCodec overrides the default event codec.

	// Example: construct a bus with a custom codec
	bus, _ := events.NewSync(events.WithCodec(nil))
	fmt.Println(bus.Driver())
	// Output: sync
}
