// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/natsevents"

func main() {
	// Config configures NATS transport construction.

	// Example: define NATS driver config
	cfg := natsevents.Config{URL: "nats://127.0.0.1:4222"}
	_ = cfg

}
