// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/natsevents"
)

func main() {
	// Ready checks that the NATS connection is healthy.

	// Example: check NATS connectivity
	driver, _ := natsevents.New(natsevents.Config{URL: "nats://127.0.0.1:4222"})
	fmt.Println(driver.Ready(context.Background()) == nil)
	// Output: true
}
