// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Ready reports whether the bus is ready.

	// Example: check readiness
	bus, _ := events.NewSync()
	fmt.Println(bus.Ready() == nil)
	// Output: true
}
