// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/redisevents"

func main() {
	// Close closes the underlying Redis client.

	// Example: close a Redis driver
	driver, _ := redisevents.New(redisevents.Config{Addr: "127.0.0.1:6379"})
	_ = driver.Close()
}
