// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// New constructs a root bus for the requested driver.

	// Example: construct a bus from config
	bus, _ := events.New(events.Config{Driver: "sync"})
	fmt.Println(bus.Driver())
	// Output: sync
}
