// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
	"github.com/goforj/events/eventscore"
)

func main() {
	// Config configures root bus construction.

	// Example: define bus construction config with all fields
	cfg := events.Config{
		Driver:    eventscore.DriverSync, // default: "sync" when empty and no Transport is provided
		Codec:     nil,                   // default: nil uses the built-in JSON codec
		Transport: nil,                   // default: nil keeps dispatch in-process
	}
	fmt.Println(cfg.Driver)
	// Output: sync
}
