//go:build benchrender
// +build benchrender

package bench

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	benchStartMarker = "<!-- bench:embed:start -->"
	benchEndMarker   = "<!-- bench:embed:end -->"
	benchRowsFile    = "benchmarks_rows.json"
)

var benchLinePattern = regexp.MustCompile(`^Benchmark([A-Za-z0-9_/]+)-\d+\s+(\d+)\s+([0-9.]+)\s+ns/op\s+(\d+)\s+B/op\s+(\d+)\s+allocs/op$`)

type benchRow struct {
	Set      string  `json:"set"`
	Name     string  `json:"name"`
	N        int     `json:"n"`
	NsOp     float64 `json:"ns_op"`
	BOp      int     `json:"b_op"`
	AllocsOp int     `json:"allocs_op"`
}

func TestDataPath(root string) string {
	return filepath.Join(root, "docs", "bench", benchRowsFile)
}

// RenderBenchmarks runs events benchmark suites, writes a benchmark snapshot,
// and injects a benchmark section into README.md.
func RenderBenchmarks() {
	root := findRepoRoot()
	rowsPath := TestDataPath(root)

	var rows []benchRow
	if os.Getenv("BENCH_RENDER_ONLY") == "1" {
		loaded, err := loadBenchmarkRows(rowsPath)
		if err != nil {
			panic(fmt.Errorf("render-only mode requires snapshot at %s: %w", rowsPath, err))
		}
		rows = loaded
	} else {
		rows = runBenchmarks(root)
		if err := saveBenchmarkRows(rowsPath, rows); err != nil {
			panic(err)
		}
	}

	rendered := renderTable(rows)
	readmePath := filepath.Join(root, "README.md")
	readmeRaw, err := os.ReadFile(readmePath)
	if err != nil {
		panic(err)
	}
	updated, err := replaceBenchBlock(string(readmeRaw), rendered)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("Benchmarks dashboard updated")
}

func runBenchmarks(root string) []benchRow {
	rows := parseRows(runBenchCommand(root, commandSpec{
		dir: root,
		args: []string{
			"test", "./...",
			"-run=^$",
			"-bench", "Benchmark(PublishNoSubscribers|PublishOneSubscriber|PublishMultipleSubscribers|ResolveTopic|NewRegisteredHandler)$",
			"-benchmem",
		},
		env: map[string]string{
			"GOCACHE": filepath.Join(root, "tmp", "gocache"),
		},
	}), "Core")

	if os.Getenv("RUN_INTEGRATION") == "1" {
		rows = append(rows, parseRows(runBenchCommand(root, commandSpec{
			dir: filepath.Join(root, "integration"),
			args: []string{
				"test", "./bench",
				"-run=^$",
				"-bench", "BenchmarkDistributedPublishRoundTrip",
				"-benchtime=1x",
				"-benchmem",
			},
			env: map[string]string{
				"GOCACHE":            filepath.Join(root, "tmp", "gocache"),
				"INTEGRATION_DRIVER": envOrDefault("INTEGRATION_DRIVER", "nats"),
			},
		}), "Integration")...)
	}

	return rows
}

type commandSpec struct {
	dir  string
	args []string
	env  map[string]string
}

func runBenchCommand(root string, spec commandSpec) string {
	cmd := exec.Command("go", spec.args...)
	cmd.Dir = spec.dir
	cmd.Env = os.Environ()
	for k, v := range spec.env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		panic(fmt.Errorf("run %q in %s failed: %w\n%s", strings.Join(spec.args, " "), strings.TrimPrefix(spec.dir, root+"/"), err, string(out)))
	}
	return string(out)
}

func parseRows(benchOutput, set string) []benchRow {
	rows := make([]benchRow, 0)
	scanner := bufio.NewScanner(strings.NewReader(benchOutput))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		m := benchLinePattern.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		rows = append(rows, parseBenchRow(set, m[1], m[2], m[3], m[4], m[5], line))
	}
	if err := scanner.Err(); err != nil {
		panic(fmt.Errorf("scan benchmark output: %w", err))
	}
	if len(rows) == 0 {
		panic(fmt.Errorf("no benchmark rows parsed for set %q", set))
	}
	return rows
}

func parseBenchRow(set, name, nStr, nsStr, bStr, allocStr, line string) benchRow {
	n, err := strconv.Atoi(nStr)
	if err != nil {
		panic(fmt.Errorf("parse N from %q: %w", line, err))
	}
	ns, err := strconv.ParseFloat(nsStr, 64)
	if err != nil {
		panic(fmt.Errorf("parse ns/op from %q: %w", line, err))
	}
	bop, err := strconv.Atoi(bStr)
	if err != nil {
		panic(fmt.Errorf("parse B/op from %q: %w", line, err))
	}
	allocs, err := strconv.Atoi(allocStr)
	if err != nil {
		panic(fmt.Errorf("parse allocs/op from %q: %w", line, err))
	}
	return benchRow{
		Set:      set,
		Name:     name,
		N:        n,
		NsOp:     ns,
		BOp:      bop,
		AllocsOp: allocs,
	}
}

func renderTable(rows []benchRow) string {
	sorted := append([]benchRow(nil), rows...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Set != sorted[j].Set {
			return sorted[i].Set < sorted[j].Set
		}
		return sorted[i].NsOp < sorted[j].NsOp
	})

	var buf bytes.Buffer
	buf.WriteString("_generated by `go test -tags=benchrender ./docs/bench -run TestRenderBenchmarks`_\n\n")
	buf.WriteString("| Class | Benchmark | ns/op | ops/s | B/op | allocs/op |\n")
	buf.WriteString("|:------|:----------|-----:|-----:|-----:|---------:|\n")
	for _, row := range sorted {
		opsPerSec := 1e9 / row.NsOp
		buf.WriteString(fmt.Sprintf(
			"| %s | `%s` | %.1f | %.0f | %d | %d |\n",
			row.Set, row.Name, row.NsOp, opsPerSec, row.BOp, row.AllocsOp,
		))
	}
	return strings.TrimSpace(buf.String())
}

func replaceBenchBlock(body, rendered string) (string, error) {
	start := strings.Index(body, benchStartMarker)
	end := strings.Index(body, benchEndMarker)
	if start == -1 || end == -1 || end < start {
		return "", fmt.Errorf("README missing %s/%s markers", benchStartMarker, benchEndMarker)
	}
	end += len(benchEndMarker)
	replacement := benchStartMarker + "\n" + rendered + "\n" + benchEndMarker
	return body[:start] + replacement + body[end:], nil
}

func saveBenchmarkRows(path string, rows []benchRow) error {
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0o644)
}

func loadBenchmarkRows(path string) ([]benchRow, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var rows []benchRow
	if err := json.Unmarshal(data, &rows); err != nil {
		return nil, err
	}
	return rows, nil
}

func envOrDefault(key, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return fallback
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Clean(filepath.Join(wd, "..", ".."))
}
