//go:build benchrender
// +build benchrender

package bench

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	benchStartMarker = "<!-- bench:embed:start -->"
	benchEndMarker   = "<!-- bench:embed:end -->"
	benchRowsFile    = "benchmarks_rows.json"
)

var benchLinePattern = regexp.MustCompile(`^Benchmark([A-Za-z0-9_/]+)-\d+\s+(\d+)\s+([0-9.]+)\s+ns/op\s+(\d+)\s+B/op\s+(\d+)\s+allocs/op$`)

type benchRow struct {
	Set      string  `json:"set"`
	Name     string  `json:"name"`
	N        int     `json:"n"`
	NsOp     float64 `json:"ns_op"`
	BOp      int     `json:"b_op"`
	AllocsOp int     `json:"allocs_op"`
}

func TestDataPath(root string) string {
	return filepath.Join(root, "docs", "bench", benchRowsFile)
}

// RenderBenchmarks runs events benchmark suites, writes a benchmark snapshot,
// renders SVG dashboard assets, and injects the benchmark section into README.md.
func RenderBenchmarks() {
	root := findRepoRoot()
	rowsPath := TestDataPath(root)

	var rows []benchRow
	if os.Getenv("BENCH_RENDER_ONLY") == "1" {
		loaded, err := loadBenchmarkRows(rowsPath)
		if err != nil {
			panic(fmt.Errorf("render-only mode requires snapshot at %s: %w", rowsPath, err))
		}
		rows = loaded
	} else {
		rows = runBenchmarks(root)
		if err := saveBenchmarkRows(rowsPath, rows); err != nil {
			panic(err)
		}
	}

	if err := writeDashboard(root, driverRows(rows)); err != nil {
		panic(err)
	}

	rendered := renderSection(rows)
	readmePath := filepath.Join(root, "README.md")
	readmeRaw, err := os.ReadFile(readmePath)
	if err != nil {
		panic(err)
	}
	updated, err := replaceBenchBlock(string(readmeRaw), rendered)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("Benchmarks dashboard updated")
}

func runBenchmarks(root string) []benchRow {
	rows := parseRows(runBenchCommand(root, commandSpec{
		dir: root,
		args: []string{
			"test", "./...",
			"-run=^$",
			"-bench", "Benchmark(PublishNoSubscribers|PublishOneSubscriber|SyncPublishRoundTrip|PublishMultipleSubscribers|ResolveTopic|NewRegisteredHandler)$",
			"-benchmem",
		},
		env: map[string]string{
			"GOCACHE": filepath.Join(root, "tmp", "gocache"),
		},
	}), "Core")

	if os.Getenv("RUN_INTEGRATION") == "1" {
		integrationEnv := map[string]string{
			"GOCACHE": filepath.Join(root, "tmp", "gocache"),
		}
		integrationEnv["INTEGRATION_DRIVER"] = integrationDriverSelection()

		rows = append(rows, parseRows(runBenchCommand(root, commandSpec{
			dir: filepath.Join(root, "integration"),
			args: []string{
				"test", "./bench",
				"-run=^$",
				"-bench", "BenchmarkDistributedPublishRoundTrip",
				"-benchtime=" + integrationBenchTime(),
				"-benchmem",
			},
			env: integrationEnv,
		}), "Integration")...)
	}

	return rows
}

type commandSpec struct {
	dir  string
	args []string
	env  map[string]string
}

func runBenchCommand(root string, spec commandSpec) string {
	cmd := exec.Command("go", spec.args...)
	cmd.Dir = spec.dir
	cmd.Env = os.Environ()
	for k, v := range spec.env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		panic(fmt.Errorf("run %q in %s failed: %w\n%s", strings.Join(spec.args, " "), strings.TrimPrefix(spec.dir, root+"/"), err, string(out)))
	}
	return string(out)
}

func parseRows(benchOutput, set string) []benchRow {
	rows := make([]benchRow, 0)
	scanner := bufio.NewScanner(strings.NewReader(benchOutput))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		m := benchLinePattern.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		rows = append(rows, parseBenchRow(set, m[1], m[2], m[3], m[4], m[5], line))
	}
	if err := scanner.Err(); err != nil {
		panic(fmt.Errorf("scan benchmark output: %w", err))
	}
	if len(rows) == 0 {
		panic(fmt.Errorf("no benchmark rows parsed for set %q", set))
	}
	return rows
}

func parseBenchRow(set, name, nStr, nsStr, bStr, allocStr, line string) benchRow {
	n, err := strconv.Atoi(nStr)
	if err != nil {
		panic(fmt.Errorf("parse N from %q: %w", line, err))
	}
	ns, err := strconv.ParseFloat(nsStr, 64)
	if err != nil {
		panic(fmt.Errorf("parse ns/op from %q: %w", line, err))
	}
	bop, err := strconv.Atoi(bStr)
	if err != nil {
		panic(fmt.Errorf("parse B/op from %q: %w", line, err))
	}
	allocs, err := strconv.Atoi(allocStr)
	if err != nil {
		panic(fmt.Errorf("parse allocs/op from %q: %w", line, err))
	}
	return benchRow{
		Set:      set,
		Name:     name,
		N:        n,
		NsOp:     ns,
		BOp:      bop,
		AllocsOp: allocs,
	}
}

func renderSection(rows []benchRow) string {
	core := coreRows(rows)
	drivers := driverRows(rows)

	var buf bytes.Buffer
	buf.WriteString("_generated by `go test -tags=benchrender ./docs/bench -run TestRenderBenchmarks`_\n\n")
	buf.WriteString("Core hot-path benchmarks track the in-process event bus overhead directly.\n")
	buf.WriteString("Backend round-trip benchmarks compare the local sync bus against every enabled broker-backed driver fixture.\n\n")

	if len(core) > 0 {
		buf.WriteString("### Core Hot Paths\n\n")
		buf.WriteString("| Benchmark | ns/op | ops/s | B/op | allocs/op |\n")
		buf.WriteString("|:----------|-----:|-----:|-----:|---------:|\n")
		for _, row := range sortCoreRows(core) {
			buf.WriteString(fmt.Sprintf(
				"| `%s` | %.1f | %.0f | %d | %d |\n",
				coreLabel(row.Name),
				row.NsOp,
				1e9/row.NsOp,
				row.BOp,
				row.AllocsOp,
			))
		}
		buf.WriteString("\n")
	}

	if len(drivers) == 0 {
		buf.WriteString("Backend charts are rendered when the benchmark snapshot includes round-trip driver rows.\n")
		buf.WriteString("Run with `RUN_INTEGRATION=1` to capture the full driver matrix.\n")
		return strings.TrimSpace(buf.String())
	}

	buf.WriteString("### Backend Round-Trip by Driver\n\n")
	buf.WriteString("These charts compare one publish-plus-delivery round trip for `sync` and each enabled distributed driver fixture.\n\n")
	buf.WriteString("Note: `gcppubsub` is excluded from the default charts because the Pub/Sub emulator is not representative enough for backend latency comparison. Benchmark it explicitly with `INTEGRATION_DRIVER=gcppubsub` when needed.\n\n")
	buf.WriteString("![Events backend latency chart](docs/bench/benchmarks_ns.svg)\n\n")
	buf.WriteString("![Events backend throughput chart](docs/bench/benchmarks_ops.svg)\n\n")
	buf.WriteString("![Events backend bytes chart](docs/bench/benchmarks_bytes.svg)\n\n")
	buf.WriteString("![Events backend allocations chart](docs/bench/benchmarks_allocs.svg)\n")

	return strings.TrimSpace(buf.String())
}

func writeDashboard(root string, rows []benchRow) error {
	if len(rows) == 0 {
		return nil
	}

	if err := writeMetricSVG(root, "benchmarks_ns.svg", "Events Backend Round-Trip Latency", "ns/op", rows, func(r benchRow) float64 {
		return r.NsOp
	}, false); err != nil {
		return err
	}
	if err := writeMetricSVG(root, "benchmarks_ops.svg", "Events Backend Round-Trip Throughput", "ops/s", rows, func(r benchRow) float64 {
		return 1e9 / r.NsOp
	}, true); err != nil {
		return err
	}
	if err := writeMetricSVG(root, "benchmarks_bytes.svg", "Events Backend Round-Trip Allocated Bytes", "B/op", rows, func(r benchRow) float64 {
		return float64(r.BOp)
	}, false); err != nil {
		return err
	}
	return writeMetricSVG(root, "benchmarks_allocs.svg", "Events Backend Round-Trip Allocations", "allocs/op", rows, func(r benchRow) float64 {
		return float64(r.AllocsOp)
	}, false)
}

func writeMetricSVG(root, filename, title, unit string, rows []benchRow, metric func(benchRow) float64, higherIsBetter bool) error {
	sorted := append([]benchRow(nil), rows...)
	sort.Slice(sorted, func(i, j int) bool {
		left := metric(sorted[i])
		right := metric(sorted[j])
		if higherIsBetter {
			if left == right {
				return driverLabel(sorted[i]) < driverLabel(sorted[j])
			}
			return left > right
		}
		if left == right {
			return driverLabel(sorted[i]) < driverLabel(sorted[j])
		}
		return left < right
	})

	maxValue := 0.0
	for _, row := range sorted {
		if value := metric(row); value > maxValue {
			maxValue = value
		}
	}
	if maxValue <= 0 {
		maxValue = 1
	}

	width := 1600
	leftPad := 260
	rightPad := 170
	topPad := 120
	barHeight := 44
	rowGap := 96
	height := topPad + barHeight + (len(sorted)-1)*rowGap + 56
	chartWidth := width - leftPad - rightPad

	var svg bytes.Buffer
	svg.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	svg.WriteString(`<svg xmlns="http://www.w3.org/2000/svg" width="` + strconv.Itoa(width) + `" height="` + strconv.Itoa(height) + `" viewBox="0 0 ` + strconv.Itoa(width) + ` ` + strconv.Itoa(height) + `">` + "\n")
	svg.WriteString(`<rect width="100%" height="100%" fill="#0f172a"/>` + "\n")
	svg.WriteString(`<text x="800" y="44" text-anchor="middle" fill="#f8fafc" font-size="34" font-family="Arial, sans-serif">` + escapeXML(title) + `</text>` + "\n")
	svg.WriteString(`<text x="800" y="80" text-anchor="middle" fill="#94a3b8" font-size="22" font-family="Arial, sans-serif">Snapshot from sync plus enabled distributed driver fixtures; ` + escapeXML(metricPreference(unit, higherIsBetter)) + `</text>` + "\n")

	for i, row := range sorted {
		y := topPad + i*rowGap
		value := metric(row)
		barWidth := int(math.Round((value / maxValue) * float64(chartWidth)))
		if barWidth < 4 {
			barWidth = 4
		}

		label := driverLabel(row)
		valueLabel := formatMetric(value, unit)
		color := driverColor(label)

		svg.WriteString(`<text x="` + strconv.Itoa(leftPad-20) + `" y="` + strconv.Itoa(y+30) + `" text-anchor="end" fill="#e2e8f0" font-size="28" font-family="Arial, sans-serif">` + escapeXML(label) + `</text>` + "\n")
		svg.WriteString(`<rect x="` + strconv.Itoa(leftPad) + `" y="` + strconv.Itoa(y) + `" width="` + strconv.Itoa(chartWidth) + `" height="` + strconv.Itoa(barHeight) + `" rx="8" fill="#1e293b"/>` + "\n")
		svg.WriteString(`<rect x="` + strconv.Itoa(leftPad) + `" y="` + strconv.Itoa(y) + `" width="` + strconv.Itoa(barWidth) + `" height="` + strconv.Itoa(barHeight) + `" rx="8" fill="` + color + `"/>` + "\n")
		svg.WriteString(`<text x="` + strconv.Itoa(leftPad+barWidth+16) + `" y="` + strconv.Itoa(y+30) + `" fill="#f8fafc" font-size="24" font-family="Arial, sans-serif">` + escapeXML(valueLabel) + `</text>` + "\n")
	}

	svg.WriteString(`</svg>` + "\n")
	return os.WriteFile(filepath.Join(root, "docs", "bench", filename), svg.Bytes(), 0o644)
}

func metricPreference(unit string, higherIsBetter bool) string {
	if higherIsBetter {
		return "higher is better (" + unit + ")"
	}
	return "lower is better (" + unit + ")"
}

func coreRows(rows []benchRow) []benchRow {
	filtered := make([]benchRow, 0, len(rows))
	for _, row := range rows {
		if row.Set == "Core" {
			filtered = append(filtered, row)
		}
	}
	return filtered
}

func integrationRows(rows []benchRow) []benchRow {
	filtered := make([]benchRow, 0, len(rows))
	for _, row := range rows {
		if row.Set == "Integration" {
			filtered = append(filtered, row)
		}
	}
	return filtered
}

func driverRows(rows []benchRow) []benchRow {
	filtered := make([]benchRow, 0, len(rows))
	selected := selectedDriverNames()
	for _, row := range rows {
		if row.Name == "SyncPublishRoundTrip" {
			filtered = append(filtered, row)
			continue
		}
		if row.Set != "Integration" {
			continue
		}
		if len(selected) == 0 || selected[driverName(row)] {
			filtered = append(filtered, row)
		}
	}
	return filtered
}

func sortCoreRows(rows []benchRow) []benchRow {
	order := map[string]int{
		"ResolveTopic":               0,
		"NewRegisteredHandler":       1,
		"PublishNoSubscribers":       2,
		"PublishOneSubscriber":       3,
		"SyncPublishRoundTrip":       4,
		"PublishMultipleSubscribers": 5,
	}

	sorted := append([]benchRow(nil), rows...)
	sort.Slice(sorted, func(i, j int) bool {
		left := order[sorted[i].Name]
		right := order[sorted[j].Name]
		if left == right {
			return sorted[i].Name < sorted[j].Name
		}
		return left < right
	})
	return sorted
}

func coreLabel(name string) string {
	switch name {
	case "ResolveTopic":
		return "ResolveTopic"
	case "NewRegisteredHandler":
		return "NewRegisteredHandler"
	case "PublishNoSubscribers":
		return "PublishNoSubscribers"
	case "PublishOneSubscriber":
		return "PublishOneSubscriber"
	case "SyncPublishRoundTrip":
		return "SyncPublishRoundTrip"
	case "PublishMultipleSubscribers":
		return "PublishMultipleSubscribers"
	default:
		return name
	}
}

func driverLabel(row benchRow) string {
	return displayDriverName(driverName(row))
}

func driverName(row benchRow) string {
	parts := strings.Split(row.Name, "/")
	if len(parts) > 1 {
		return parts[len(parts)-1]
	}
	return row.Name
}

func displayDriverName(name string) string {
	switch name {
	case "SyncPublishRoundTrip":
		return "Sync"
	case "gcppubsub":
		return "Google Pub/Sub"
	case "kafka":
		return "Kafka"
	case "nats":
		return "NATS"
	case "redis":
		return "Redis"
	default:
		return name
	}
}

func driverColor(label string) string {
	switch label {
	case "Sync":
		return "#546E7A"
	case "Google Pub/Sub":
		return "#4285F4"
	case "Kafka":
		return "#231F20"
	case "NATS":
		return "#27AAE1"
	case "Redis":
		return "#DC382D"
	default:
		return "#38BDF8"
	}
}

func formatMetric(value float64, unit string) string {
	switch unit {
	case "ns/op":
		return fmt.Sprintf("%.0f %s", value, unit)
	case "ops/s":
		return fmt.Sprintf("%.0f %s", value, unit)
	case "B/op":
		return fmt.Sprintf("%.0f %s", value, unit)
	case "allocs/op":
		return fmt.Sprintf("%.0f %s", value, unit)
	default:
		return fmt.Sprintf("%.1f %s", value, unit)
	}
}

func escapeXML(value string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&apos;",
	)
	return replacer.Replace(value)
}

func replaceBenchBlock(body, rendered string) (string, error) {
	start := strings.Index(body, benchStartMarker)
	end := strings.Index(body, benchEndMarker)
	if start == -1 || end == -1 || end < start {
		return "", fmt.Errorf("README missing %s/%s markers", benchStartMarker, benchEndMarker)
	}
	end += len(benchEndMarker)
	replacement := benchStartMarker + "\n" + rendered + "\n" + benchEndMarker
	return body[:start] + replacement + body[end:], nil
}

func saveBenchmarkRows(path string, rows []benchRow) error {
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0o644)
}

func loadBenchmarkRows(path string) ([]benchRow, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var rows []benchRow
	if err := json.Unmarshal(data, &rows); err != nil {
		return nil, err
	}
	return rows, nil
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Clean(filepath.Join(wd, "..", ".."))
}

func integrationBenchTime() string {
	if value := strings.TrimSpace(os.Getenv("BENCH_INTEGRATION_TIME")); value != "" {
		return value
	}
	return "1s"
}

func integrationDriverSelection() string {
	if value := strings.TrimSpace(os.Getenv("INTEGRATION_DRIVER")); value != "" {
		return value
	}
	return "kafka,nats,redis"
}

func selectedDriverNames() map[string]bool {
	value := integrationDriverSelection()
	if value == "" {
		return nil
	}
	selected := make(map[string]bool)
	for _, part := range strings.Split(value, ",") {
		part = strings.TrimSpace(strings.ToLower(part))
		if part != "" {
			selected[part] = true
		}
	}
	return selected
}
