// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Record captures one published event observed by a Fake bus.

	// Example: inspect a recorded event
	type UserCreated struct {
		ID string `json:"id"`
	}

	record := events.Record{Event: UserCreated{ID: "123"}}
	fmt.Printf("%T\n", record.Event)
	// Output: main.UserCreated
}
