// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/gcppubsubevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// SubscribeContext subscribes to a Google Pub/Sub topic and forwards messages.

	// Example: subscribe to a Google Pub/Sub topic
	driver, _ := gcppubsubevents.New(context.Background(), gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	})
	sub, _ := driver.SubscribeContext(context.Background(), "users.created", func(ctx context.Context, msg eventscore.Message) error {
		_ = ctx
		_ = msg
		return nil
	})
	fmt.Println(sub != nil)
	// Output: true
}
