// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Driver reports the active bus backend.

	// Example: inspect the active backend through the interface
	api, _ := events.NewSync()
	var bus events.API = api
	fmt.Println(bus.Driver())
	// Output: sync
}
