// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// API is the root application-facing bus contract.

	// Example: keep an API-typed bus reference
	api, _ := events.NewSync()
	var bus events.API = api
	fmt.Println(bus.Driver())
	// Output: sync
}
