// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
	"github.com/goforj/events/eventscore"
)

func main() {
	// Config configures root bus construction.

	// Example: define bus construction config
	cfg := events.Config{Driver: eventscore.DriverSync}
	fmt.Println(cfg.Driver)
	// Output: sync

}
