// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/natsevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// SubscribeContext subscribes to a NATS subject and forwards messages.

	// Example: subscribe to a raw NATS subject
	driver, _ := natsevents.New(natsevents.Config{URL: "nats://127.0.0.1:4222"})
	sub, _ := driver.SubscribeContext(context.Background(), "users.created", func(ctx context.Context, msg eventscore.Message) error {
		_ = ctx
		_ = msg
		return nil
	})
	fmt.Println(sub != nil)
	// Output: true
}
