// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Publish dispatches an event with the background context.

	// Example: publish a typed event through the interface
	type UserCreated struct {
		ID string `json:"id"`
	}

	api, _ := events.NewSync()
	var bus events.API = api
	_, _ = bus.Subscribe(func(event UserCreated) {
		fmt.Println(event.ID)
	})
	_ = bus.Publish(UserCreated{ID: "123"})
	// Output: 123
}
