// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/kafkaevents"
)

func main() {
	// Driver is a Kafka-backed events transport.

	// Example: keep a Kafka driver reference
	var driver *kafkaevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
