// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Option configures root bus behavior.

	// Example: keep an option for later bus construction
	opt := events.WithCodec(nil)
	fmt.Println(opt != nil)
	// Output: true
}
