// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/redisevents"
)

func main() {
	// Driver is a Redis pub/sub-backed events transport.

	// Example: keep a Redis driver reference
	var driver *redisevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
