// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"github.com/goforj/events"
	"github.com/goforj/events/driver/natsjetstreamevents"
	"time"
)

func main() {
	// Config configures NATS JetStream transport construction.

	// Example: define NATS JetStream driver config with all fields
	cfg := natsjetstreamevents.Config{
		URL:               "nats://127.0.0.1:4222",
		Conn:              nil,                     // default: nil dials URL instead of reusing an existing connection
		SubjectPrefix:     "events.",               // default: "events."
		StreamNamePrefix:  "EVENTS_",               // default: "EVENTS_"
		InactiveThreshold: 30 * time.Second,        // default: 30s
		AckWait:           30 * time.Second,        // default: 30s
		FetchMaxWait:      250 * time.Millisecond,  // default: 250ms
		Storage:           jetstream.MemoryStorage, // default: MemoryStorage
	}
	_ = cfg
}
