// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Publish publishes an event using the background context.

	// Example: publish a typed event
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	_, _ = bus.Subscribe(func(event UserCreated) {
		fmt.Println(event.ID)
	})
	_ = bus.Publish(UserCreated{ID: "123"})
	// Output: 123
}
