// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/natsjetstreamevents"

func main() {
	// New connects a NATS JetStream-backed driver from config.

	// Example: construct a NATS JetStream driver
	driver, _ := natsjetstreamevents.New(natsjetstreamevents.Config{URL: "nats://127.0.0.1:4222"})
	_ = driver
}
