// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// ReadyContext performs a readiness check with the provided context.

	// Example: check readiness with a caller context
	api, _ := events.NewSync()
	var bus events.API = api
	fmt.Println(bus.ReadyContext(context.Background()) == nil)
	// Output: true
}
