// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/natsevents"

func main() {
	// New connects a NATS-backed driver from config.

	// Example: construct a NATS driver
	driver, _ := natsevents.New(natsevents.Config{URL: "nats://127.0.0.1:4222"})
	_ = driver
}
