// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/gcppubsubevents"

func main() {
	// Config configures Google Pub/Sub transport construction.

	// Example: define Google Pub/Sub driver config with all fields
	cfg := gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085", // default: "" is invalid unless Client is provided
		Client:    nil,              // default: nil creates a client from ProjectID and URI
	}
	_ = cfg
}
