// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Subscribe registers a handler using the background context.

	// Example: subscribe to a typed event
	type UserCreated struct {
		ID string `json:"id"`
	}

	bus, _ := events.NewSync()
	sub, _ := bus.Subscribe(func(ctx context.Context, event UserCreated) error {
		fmt.Println(event.ID)
		return nil
	})
	defer sub.Close()
	_ = bus.Publish(UserCreated{ID: "123"})
	// Output: 123
}
