// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/natsevents"
)

func main() {
	// Driver is a NATS-backed events transport.

	// Example: keep a NATS driver reference
	var driver *natsevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
