// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Reset clears recorded publishes.

	// Example: clear recorded publishes
	type UserCreated struct {
		ID string `json:"id"`
	}

	fake := events.NewFake()
	_ = fake.Bus().Publish(UserCreated{ID: "123"})
	fake.Reset()
	fmt.Println(fake.Count())
	// Output: 0
}
