// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/natsevents"
)

func main() {
	// Config configures NATS transport construction.

	// Example: define NATS driver config with all fields
	cfg := natsevents.Config{
		URL:  "nats://127.0.0.1:4222",
		Conn: nil, // default: nil dials URL instead of reusing an existing connection
	}
	fmt.Println(cfg.URL)
	// Output: nats://127.0.0.1:4222
}
