// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/redisevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// PublishContext publishes a topic payload via Redis pub/sub.

	// Example: publish a raw message through Redis
	driver, _ := redisevents.New(redisevents.Config{Addr: "127.0.0.1:6379"})
	_ = driver.PublishContext(context.Background(), eventscore.Message{
		Topic:   "users.created",
		Payload: []byte(`{"id":"123"}`),
	})
}
