// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/snsevents"
)

func main() {
	// Driver is an SNS-backed events transport using SQS queues for subscriptions.

	// Example: keep an SNS driver reference
	var driver *snsevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
