// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Bus is the root event bus implementation.

	// Example: keep a concrete bus reference
	bus, _ := events.NewSync()
	var root *events.Bus = bus
	fmt.Println(root.Driver())
	// Output: sync
}
