// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/kafkaevents"

func main() {
	// Driver reports the active backend kind.

	// Example: inspect the driver kind
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	_ = driver
}
