// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/redisevents"
	"github.com/goforj/events/eventscore"
)

func main() {
	// SubscribeContext subscribes to a Redis pub/sub channel.

	// Example: subscribe to a Redis channel
	driver, _ := redisevents.New(redisevents.Config{Addr: "127.0.0.1:6379"})
	sub, _ := driver.SubscribeContext(context.Background(), "users.created", func(ctx context.Context, msg eventscore.Message) error {
		_ = ctx
		_ = msg
		return nil
	})
	fmt.Println(sub != nil)
	// Output: true
}
