// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// Codec marshals and unmarshals event payloads.

	// Example: define a custom codec
	var codec events.Codec
	fmt.Println(codec == nil)
	// Output: true
}
