// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/natsjetstreamevents"
)

func main() {
	// Driver is a NATS JetStream-backed events transport.

	// Example: keep a NATS JetStream driver reference
	var driver *natsjetstreamevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
