// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/kafkaevents"
)

func main() {
	// Ready checks Kafka connectivity.

	// Example: check Kafka connectivity
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	fmt.Println(driver.Ready(context.Background()) == nil)
	// Output: true
}
