// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/events/driver/gcppubsubevents"
)

func main() {
	// Ready checks Google Pub/Sub connectivity.

	// Example: check Google Pub/Sub connectivity
	driver, _ := gcppubsubevents.New(context.Background(), gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	})
	fmt.Println(driver.Ready(context.Background()) == nil)
	// Output: true
}
