// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/gcppubsubevents"
)

func main() {
	// Driver reports the active backend kind.

	// Example: inspect the driver kind
	driver, _ := gcppubsubevents.New(context.Background(), gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	})
	_ = driver
}
