// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/gcppubsubevents"
)

func main() {
	// Config configures Google Pub/Sub transport construction.

	// Example: define Google Pub/Sub driver config
	cfg := gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	}
	fmt.Println(cfg.ProjectID)
	// Output: events-project

}
