// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events/driver/gcppubsubevents"
)

func main() {
	// Driver is a Google Pub/Sub-backed events transport.

	// Example: keep a Google Pub/Sub driver reference
	var driver *gcppubsubevents.Driver
	fmt.Println(driver == nil)
	// Output: true
}
