// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/events/driver/gcppubsubevents"
)

// main keeps this generated example compile-checked.
func main() {
	// New constructs a Google Pub/Sub-backed driver.

	// Example: construct a Google Pub/Sub driver
	driver, _ := gcppubsubevents.New(context.Background(), gcppubsubevents.Config{
		ProjectID: "events-project",
		URI:       "127.0.0.1:8085",
	})
	_ = driver
}
