// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

// main keeps this generated example compile-checked.
func main() {
	// Fake provides a root-package testing helper that records published events.

	// Example: keep a fake for assertions in tests
	fake := events.NewFake()
	fmt.Println(fake.Count())
	// Output: 0
}
