// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/kafkaevents"

// main keeps this generated example compile-checked.
func main() {
	// Close closes the underlying Kafka writer.

	// Example: close a Kafka driver
	driver, _ := kafkaevents.New(kafkaevents.Config{Brokers: []string{"127.0.0.1:9092"}})
	_ = driver.Close()
}
