// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/events/driver/natsevents"

func main() {
	// Close drains the underlying NATS connection.

	// Example: close a NATS driver
	driver, _ := natsevents.New(natsevents.Config{URL: "nats://127.0.0.1:4222"})
	_ = driver.Close()
}
