// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

// main keeps this generated example compile-checked.
func main() {
	// Driver reports the active backend.

	// Example: inspect the active backend
	bus, _ := events.NewSync()
	fmt.Println(bus.Driver())
	// Output: sync
}
