// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

// main keeps this generated example compile-checked.
func main() {
	// Records returns a copy of recorded publishes.

	// Example: inspect recorded publishes
	type UserCreated struct {
		ID string `json:"id"`
	}

	fake := events.NewFake()
	_ = fake.Bus().Publish(UserCreated{ID: "123"})
	fmt.Println(len(fake.Records()))
	// Output: 1
}
