// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/events"
)

func main() {
	// NewNull constructs the root null bus.

	// Example: construct a null bus
	bus, _ := events.NewNull()
	fmt.Println(bus.Driver())
	// Output: null
}
